name: Release Helm Chart

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, such as v1.2.3 tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from tag
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/admin-dashboard.tgz
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
