name: Release Helm Chart

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, such as v1.2.3 tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/admin-dashboard-0.0.1.tgz # Update with the correct path to your .tgz file
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
